/* eslint-disable react-native/no-color-literals */
import {
    black,
    brightGrey,
    charcoalGrey,
    defaultGrey,
    firstColor,
    greenColor,
    itemGrey,
    listGrey,
    mediumGrey,
    selectedItemGreen,
} from './Colors';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    headerImage: {
        color: firstColor,
        bottom: -90,
        left: -35,
        position: 'absolute',
    },
    titleContainer: {
        flexDirection: 'row',
        gap: 8,
    },
    defaultImage: {
        alignSelf: 'center',
    },
    dafaultThemedText: {
        fontFamily: 'SpaceMono',
    },
    container: {
        flex: 1,
        backgroundColor: defaultGrey,
    },
    narrowBox: {
        width: '50%',
        height: 50,
        backgroundColor: brightGrey,
        borderRadius: 10,
        padding: 10,
        marginBottom: 30,
        alignSelf: 'center',
        marginTop: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    defaultBox: {
        width: '80%',
        backgroundColor: brightGrey,
        borderRadius: 10,
        padding: 10,
        marginBottom: 30,
        alignSelf: 'center',
        marginTop: 30,
    },
    titleTextBox: {
        fontSize: 24,
        fontWeight: 'bold',
        color: charcoalGrey,
        fontFamily: 'SpaceMono',
        textAlign: 'center',
    },
    textBox: {
        fontSize: 24,
        color: black,
        fontFamily: 'SpaceMono',
        textAlign: 'center',
        flex: 1,
    },
    inputBox: {
        width: '80%',
        height: 200,
        backgroundColor: 'white',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#333',
        padding: 10,
        marginBottom: 20,
        alignSelf: 'center',
        marginTop: 50,
    },
    thesisTitleBox: {
        width: '80%',
        height: 210,
        backgroundColor: brightGrey,
        borderRadius: 10,
        padding: 10,
        marginBottom: 30,
        alignSelf: 'center',
        marginTop: 30,
    },
    thesisDescriptionBox: {
        width: '80%',
        height: 700,
        backgroundColor: brightGrey,
        borderRadius: 10,
        padding: 10,
        marginBottom: 30,
        alignSelf: 'center',
        marginTop: 30,
    },
    signInButton: {
        backgroundColor: greenColor,
        alignSelf: 'flex-end',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    addThesesButton: {
        backgroundColor: greenColor,
        alignSelf: 'center',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    deleteButton: {
        backgroundColor: 'red',
        alignSelf: 'center',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
        marginTop: 10,
    },

    buttonText: {
        color: 'white',
        fontSize: 24,
        fontWeight: 'bold',
    },
    slotValue: {
        fontWeight: 'bold',
    },
    supervisorBox: {
        width: '80%',
        backgroundColor: brightGrey,
        borderBottomWidth: 1,
        borderBottomColor: mediumGrey,
        alignSelf: 'center',
        padding: 10,
        borderRadius: 10,
    },
    pageTitile: {
        fontSize: 48,
        fontWeight: 'bold',
        color: greenColor,
        fontFamily: 'SpaceMono',
        textAlign: 'center',
        marginTop: 50,
        marginBottom: 50,
    },
    filterHeader: {
        padding: 10,
        backgroundColor: brightGrey,
        borderRadius: 8,
        marginVertical: 10,
        width: '80%',
        alignSelf: 'center',
    },
    filterList: {
        marginVertical: 10,
        width: '80%',
        alignSelf: 'center',
        backgroundColor: listGrey,
        borderRadius: 10,
    },
    selectedFilters: {
        marginVertical: 10,
        width: '80%',
        alignSelf: 'center',
    },
    filterItem: {
        padding: 10,
        marginVertical: 5,
        backgroundColor: itemGrey,
        borderRadius: 8,
    },
    filterItemSelected: {
        backgroundColor: selectedItemGreen,
    },
    tagList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginVertical: 10,
        width: '80%',
        alignSelf: 'center',
        backgroundColor: listGrey,
        borderRadius: 20,
    },
    tagItem: {
        backgroundColor: itemGrey,
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 10,
        margin: 5,
    },
    tagItemSelected: {
        backgroundColor: '#aed581',
    },
    marginTop10: {
        marginTop: 10,
    },
    applyFiltersButton: {
        backgroundColor: greenColor,
        alignItems: 'center',
        alignSelf: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 20,
    },
    selectedTagsBox: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 8,
        alignSelf: 'center',
        width: '80%',
    },
    selectedTagText: {
        backgroundColor: '#e0e0e0',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 12,
        marginRight: 8,
        marginBottom: 8,
        fontSize: 20,
    },
    freeSpace: {
        height: 50,
    },
    drawerMenuTextStyle: {
        borderRadius: 0,
        fontWeight: 'bold',
        color: black,
    },
    drawerItemStyle: {
        borderTopWidth: 1,
        borderColor: black,
        width: '100%',
    },
    headerTextStyle: {
        color: listGrey,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    mainCustomDrawerStyle: {
        flex: 1,
        backgroundColor: greenColor,
    },
    firstCustomDrawerStyle: {
        marginTop: 30,
        flex: 1,
    },
    secondCustomDrawerStyle: {
        flex: 21,
        marginLeft: 0,
    },
    drawerHeader: {
        marginLeft: 15,
    },
    menuNameStyle: {
        color: listGrey,
        textAlign: 'center',
        fontSize: 40,
    },
    loginContainer: {
        padding: 24,
        flex: 1,
        justifyContent: 'center',
    },
    loginLabel: {
        fontSize: 20,
        marginBottom: 4,
    },
    loginInput: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 6,
        padding: 12,
        marginBottom: 16,
        fontSize: 20,
    },
    loginButtonContainer: {
        marginTop: 8,
    },
    loginError: {
        marginTop: 12,
        color: 'red',
        fontWeight: '600',
    },
    activeLabelStyle: {
        color: listGrey,
        fontWeight: 'bold' as const,
        marginLeft: 10,
        fontSize: 24,
        lineHeight: 30,
        paddingVertical: 4,
    },
    inactiveLabelStyle: {
        color: listGrey,
        fontWeight: 'normal' as const,
        marginLeft: 10,
        fontSize: 24,
        lineHeight: 30,
        paddingVertical: 4,
    },
    activeItemStyle: {
        backgroundColor: selectedItemGreen,
        borderTopWidth: 1,
        borderColor: black,
        flexShrink: 1,
        paddingRight: 16,
    },
    inactiveItemStyle: {
        backgroundColor: 'transparent',
        borderTopWidth: 1,
        borderColor: black,
    },
    loadingStyle: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    mainStudentListBox: {
        width: '80%',
        backgroundColor: brightGrey,
        borderRadius: 10,
        padding: 10,
        marginBottom: 30,
        alignSelf: 'center',
        marginTop: 30,
        paddingBottom: 16,
    },
    titleStudentListText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: charcoalGrey,
        fontFamily: 'SpaceMono',
        textAlign: 'center',
        marginBottom: 8,
    },
    singleElementFormStudentList: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
        width: '100%',
    },
    declineButton: {
        backgroundColor: 'crimson',
        alignSelf: 'flex-end',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    flexViewStyle: {
        flexDirection: 'row',
        gap: 8,
    },
    subtitle: {
        fontSize: 32,
        textAlign: 'center',
        fontFamily: 'SpaceMono',
    },
    redText: {
        color: 'red',
    },
    normalText: {
        color: black,
    },
});
