# Generated by Django 5.2 on 2025-04-29 23:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('index_number', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bacherol_limit', models.IntegerField(default=1)),
                ('engineering_limit', models.IntegerField(default=1)),
                ('master_limit', models.IntegerField(default=1)),
                ('phd_limit', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(related_name='users', to='common.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_title',
            field=models.CharField(blank=True, choices=[('brak', 'Brak'), ('inżynier', 'Inżynier'), ('licencjat', 'Licencjat'), ('magister', 'Magister'), ('doktor', 'Doktor'), ('doktor habilitowany', 'Doktor habilitowany'), ('profesor', 'Profesor')], default='brak', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('promotor', 'Promotor'), ('koordynator wydziału', 'Koordynator wydziału'), ('admin', 'Admin')], default='student', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
