name: Django Tests

on:
  push:
    branches: [ '**' ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and start Docker Compose services
      run: |
        docker compose build
        docker compose up -d db
        
    - name: Wait for database to be ready
      run: |
        sleep 10
        
    - name: Run tests in Docker
      run: |
        docker compose run backend python manage.py test
        
    - name: Clean up
      run: docker compose down
      if: always() 