name: Django Tests
on:
  push:
    branches: [ '**' ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Debug directory structure
      run: |
        echo "Current directory:"
        pwd
        echo "Contents of current directory:"
        ls -la
        echo "Contents of backend directory:"
        ls -la backend
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and start Docker Compose services
      run: |
        cd backend
        echo "Working in $(pwd)"
        ls -la
        docker compose build
        docker compose up -d
    
    - name: Wait for database to be ready
      run: |
        cd backend
        sleep 10
    
    - name: Run tests in Docker
      run: |
        cd backend
        docker compose exec -T backend python manage.py test
    
    - name: Clean up
      if: always()
      run: |
        cd backend
        docker compose down
